services:
#    blog.example:
#        class: Blog\BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
     register:
         class: Blog\BlogBundle\Form\TaskType
         tags:
         -  { name: form.type }